<?php
$dictionary['Lead']['fields']['media_agency'] = array(
    'required' => false,
    'name' => 'media_agency',
    'vname' => 'LBL_MEDIA_AGENCY',
    'type' => 'enum',
    'massupdate' => true,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '30',
    'options' => 'lead_media_agency_list',
    'studio' => 'visible',
    'dependency' => false,
    'readonly' => false,
);