<?php
$dictionary['Lead']['fields']['priority_merged_industries'] = array(
    'required' => false,
    'name' => 'priority_merged_industries',
    'vname' => 'LBL_PRIORITY_MERGED_INDUSTRIES',
    'type' => 'enum',
    'massupdate' => true,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'priority_merged_industries_list',
    'studio' => 'visible',
    'dependency' => false,
    'readonly' => true,
);
