<?php
$dictionary['Opportunity']['fields']['business_cluster'] = array(
    'required' => false,
    'name' => 'business_cluster',
    'vname' => 'LBL_BUSINESS_CLUSTER',
    'type' => 'enum',
    'massupdate' => false,
    'default' => '',
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'enabled',
    'duplicate_merge_dom_value' => '1',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '30',
    'options' => 'lead_businesscluster_list',
    'studio' => 'visible',
    'dependency' => false,
    'readonly' => false,
);
